module.exports = (sequelize, DataTypes) => {
	return sequelize.define(
		'paymentLog',
		{
			esntlId: {
				type: DataTypes.STRING(50),
				allowNull: false,
				primaryKey: true,
				field: 'esntlId',
				comment: '고유아이디',
			},
			pDate: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'pDate',
				comment: '결제 날짜',
			},
			pTime: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'pTime',
				comment: '결제 시간',
			},
			withdrawalStatus: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'withdrawalStatus',
				comment: '결제 취소 여부',
			},
			paymentType: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'paymentType',
				comment: '결제 종류',
			},
			contractEsntlId: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'contractEsntlId',
				comment: '계약 고유아이디',
			},
			gosiwonEsntlId: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'gosiwonEsntlId',
				comment: '고시원아이디',
			},
			roomEsntlId: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'roomEsntlId',
				comment: '룸아이디',
			},
			customerEsntlId: {
				type: DataTypes.STRING(50),
				allowNull: false,
				defaultValue: '',
				field: 'customerEsntlId',
				comment: '고객 고유아이디',
			},
			extrapayEsntlId: {
				type: DataTypes.STRING(50),
				allowNull: true,
				defaultValue: null,
				field: 'extrapayEsntlId',
				comment: '추가 결제 고유아이디 (extraPayment.esntlId 참조, 값 있으면 추가결제)',
			},
			paymentAmount: {
				type: DataTypes.STRING(50),
				allowNull: false,
				defaultValue: '0',
				field: 'paymentAmount',
				comment: '결제 금액',
			},
			discountAmount: {
				type: DataTypes.STRING(50),
				allowNull: false,
				defaultValue: '0',
				field: 'discountAmount',
				comment: '할인 금액',
			},
			paymentPoint: {
				type: DataTypes.STRING(50),
				allowNull: false,
				defaultValue: '0',
				field: 'paymentPoint',
				comment: '결제시 사용한 포인트',
			},
			paymentCoupon: {
				type: DataTypes.STRING(50),
				allowNull: false,
				defaultValue: '0',
				field: 'paymentCoupon',
				comment: '결제시 사용한 쿠폰',
			},
			ucp_eid: {
				type: DataTypes.STRING(14),
				allowNull: true,
				field: 'ucp_eid',
				comment: '사용자쿠폰고유아이디',
			},
			collectPoint: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'collectPoint',
				comment: '적립 포인트',
			},
			code: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'code',
				comment: '성공여부 코드',
			},
			reason: {
				type: DataTypes.STRING(200),
				allowNull: true,
				field: 'reason',
				comment: '실패시 이유',
			},
			calAmount: {
				type: DataTypes.STRING(20),
				allowNull: false,
				defaultValue: '',
				field: 'calAmount',
				comment: '수수료기준금액',
			},
			pyl_goods_amount: {
				type: DataTypes.INTEGER(11),
				allowNull: false,
				defaultValue: 0,
				field: 'pyl_goods_amount',
				comment: '상품금액(원입실료)',
			},
			imp_uid: {
				type: DataTypes.STRING(50),
				allowNull: false,
				field: 'imp_uid',
				comment: 'PG',
			},
			cAmount: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'cAmount',
				comment: '수수료',
			},
			cPercent: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'cPercent',
				comment: '수수료(%)',
			},
			calculateStatus: {
				type: DataTypes.STRING(50),
				allowNull: true,
				field: 'calculateStatus',
				comment: '결제상태',
			},
			tid: {
				type: DataTypes.STRING(30),
				allowNull: true,
				field: 'tid',
				comment: '승인아이디(PG)',
			},
			pyl_expected_settlement_date: {
				type: DataTypes.STRING(10),
				allowNull: true,
				field: 'pyl_expected_settlement_date',
				comment: '정산예정일',
			},
			pyl_contract_data: {
				type: DataTypes.TEXT,
				allowNull: true,
				field: 'pyl_contract_data',
				comment: '결제데이터',
			},
			// 추가 결제 관련 컬럼
			extraCostName: {
				type: DataTypes.STRING(200),
				allowNull: true,
				field: 'extraCostName',
				comment: '추가비용명칭 (주차비, 추가 입실료, 직접 입력 등)',
			},
			memo: {
				type: DataTypes.TEXT,
				allowNull: true,
				field: 'memo',
				comment: '메모 (ex. 2인 추가 / 정가 계산 등)',
			},
			optionInfo: {
				type: DataTypes.STRING(200),
				allowNull: true,
				field: 'optionInfo',
				comment: '옵션정보 (주차비의 경우 차량정보, 직접 입력의 경우 옵션명 등)',
			},
			useStartDate: {
				type: DataTypes.DATEONLY,
				allowNull: true,
				field: 'useStartDate',
				comment: '이용 시작 일자 (주차비, 직접 입력의 경우)',
			},
			optionName: {
				type: DataTypes.STRING(200),
				allowNull: true,
				field: 'optionName',
				comment: '옵션명 (직접 입력의 경우)',
			},
			extendWithPayment: {
				type: DataTypes.TINYINT(1),
				allowNull: false,
				defaultValue: 0,
				field: 'extendWithPayment',
				comment: '연장시 함께 결제 여부 (0: 미사용, 1: 사용)',
			},
		},
		{
			tableName: 'paymentLog',
			timestamps: false,
			freezeTableName: true,
		}
	);
};
